name = "PolyBr"
uuid = "3c307872-14e4-494b-abb3-fed68641e9b4"
authors = ["Guy Van den Broeck <guyvdb@gmail.com>"]
version = "0.1.0"

[deps]
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"

[compat]
IRTools = "0.4"
IfElse = "0.1"
